# filepath: /.github/workflows/processScheduledPosts.yml
name: Process Scheduled Posts

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  process_posts:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Process Scheduled Posts API
        run: |
          curl -X POST https://your-vercel-app.vercel.app/api/processScheduledPosts
