name: Process Scheduled Posts

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  process_posts:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Process Scheduled Posts API
        run: |
          curl -X POST https://software-engineering-project-eight.vercel.app/api/instagram/cron
